### ISSUE TITLE
demos are giving non-zero exit codes when compiled

### ISSUE THREAD

**Issue by xiaket** [goplus/llgo#156]
I've setup my `LLGOROOT` to the repo directory, `export LLGOROOT="/Users/kai/.Github/llgo"`, then I compiled all the code under `_demo`, this works:

```
for i in *; do (cd $i; llgo build .); done
```

However, when we run these commands, it all failed with different exit codes:

```
{🏠? ~/.xia/sha/git/llg/_demo}for i in *; do ./$i/$i > /dev/null 2>&1 ; echo $i $?; done
concat 16
genints 2
hello 12
llama2-c 1
qsort 4
sqlite 1
```

After some inspection, it looks like most of the code runs successfully, it is just not exiting with zero code. Running via `llgo run` does not have this issue.

**Comment by xushiwei** [comment]
Thanks for the feedback. It seems that because the main function executes `ret void` at the end, the return value of the last statement is returned as the exit code. For example, the last statement printf of `concat` returns the number of printed characters 16, so the exit code becomes 16.

**Comment by xushiwei** [comment]
solved
