### ISSUE TITLE
Readme isn't super clear how to set `LLGO_LIB_PYTHON`

### ISSUE THREAD

**Issue by xiaket** [goplus/llgo#157]
In my case, I have python 3.11 installed via Homebrew, I have the following directory structure:

```
{🏠 /opt/hom/Cel/pyt/3.1/Fra/Pyt/Ver/3.11}pwd
/opt/homebrew/Frameworks/Python.framework/Versions/3.11
{🏠 /opt/hom/Cel/pyt/3.1/Fra/Pyt/Ver/3.11}ls -l
total 4.8M
drwxr-xr-x 3 kai admin   96 Feb  7 08:21 share
drwxr-xr-x 5 kai admin  160 Feb  7 08:21 lib
drwxr-xr-x 3 kai admin   96 Feb  7 08:21 include
drwxr-xr-x 3 kai admin   96 Feb  7 08:21 _CodeSignature
drwxr-xr-x 4 kai admin  128 Feb  7 08:21 Resources
lrwxr-xr-x 1 kai admin   18 Feb  7 08:21 Headers -> include/python3.11
-rwxr-xr-x 1 kai admin 4.8M Mar  7 22:37 Python
drwxr-xr-x 9 kai admin  288 Mar  7 22:37 bin
```

And in my lib folder I can find  the dylib file:

```
{🏠 /opt/hom/Cel/pyt/3.1/Fra/Pyt/Ver/3.1/lib}ls
total 0
lrwxr-xr-x   1 kai admin    9 Feb  7 08:21 libpython3.11.dylib -> ../Python
drwxr-xr-x   4 kai admin  128 Mar  7 22:37 pkgconfig
drwxr-xr-x 209 kai admin 6.6K Mar  7 22:37 python3.11
```

When I set `LLGO_LIB_PYTHON` to `/opt/homebrew/Frameworks/Python.framework/Versions/3.11/lib`, `llgo` is not able to correctly link things:

```
{🏠? ~/.xia/sha/git/llg/_py/callpy}LLGO_LIB_PYTHON=/opt/homebrew/Frameworks/Python.framework/Versions/3.11/lib llgo run .
ld: library 'lib' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

When I however set it to `/opt/homebrew/Frameworks/Python.framework/Versions/3.11/lib/python3.11`, it runs without issue:

```
{🏠? ~/.xia/sha/git/llg/_py/callpy}LLGO_LIB_PYTHON=/opt/homebrew/Frameworks/Python.framework/Versions/3.11/lib/python3.11 llgo run .
sqrt(2) = 1.414214
```

Also I think it would also make sense to mention setting `LLGOROOT` in the doc.

**Comment by xushiwei** [comment]
export LLGO_LIB_PYTHON=/opt/homebrew/Frameworks/Python.framework/Versions/3.11/lib/python3.11

**Comment by xiaket** [comment]
BTW I should mention `/opt/homebrew/Frameworks/Python.framework/Versions/3.11/lib/python3.11` is the folder that contains all the python standard lib, for example, `socket.py`  can be found under that 3.11 directory:

```
{🏠 /opt/hom/Cel/pyt/3.1/Fra/Pyt/Ver/3.1/lib}ls -l /opt/homebrew/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py
-rw-r--r-- 1 kai admin 37K Feb  7 08:21 /opt/homebrew/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py
```

**Comment by xushiwei** [comment]
Sorry for causing trouble to you. `LLGO_LIB_PYTHON` is actually a pseudo file name, which is decomposed into `<dir>` and `<fname>` parts. The actual filename for the `<fname>` part will vary between platforms. For example, under mac it will become `lib<fname>.dylib`, under linux it will become `lib<fname>.so`.

**Comment by xushiwei** [comment]
document updated
