### ISSUE TITLE
Problem when installing LLGO on MAC OS 11

### ISSUE THREAD

**Issue by spongehah** [goplus/llgo#354]
When executing the "brew install llvm@17 pkg-config libgc" command when installing LLGO on MAC OS11, there will be no progress for a long time and the installation cannot be successful. The problem is solved after updating to MAC OS 13.6.7

**Comment by aofei** [comment]
> there will be no progress for a long time and the installation cannot be successful.

Sounds like a network access issue. Try using a different network or a VPN.

**Comment by spongehah** [comment]
> > there will be no progress for a long time and the installation cannot be successful.
> 
> Sounds like a network access issue. Try using a different network or a VPN.

I tried it, but the same situation still occurred. Because an old version system warning appeared when executing the command, I tried to update the system and succeeded. People around me also succeeded after updating the system.

**Comment by aisk** [comment]
homebrew didn't provide bottle for macOS 11 aka BigSur: https://github.com/Homebrew/homebrew-core/blob/e2cf81a217c17a19acf5bc3bbc4579109d815b38/Formula/l/llvm%4017.rb#L14-L22

So when you install it, homebrew will try to build it from source, which take a very long time depending on your CPU, and usually get failed by OOM.
