### ISSUE TITLE
alpine linux llgo run demo panic

### ISSUE THREAD

**Issue by 8923052** [goplus/llgo#910]
1、os
alpine linux 3.21

2、llgo version
`llgo v0.9.8 linux/amd64`

3、code
package main

import "github.com/goplus/llgo/c"

func main() {
	c.Printf(c.Str("Hello world\n"))
}

4、llgo run .
panic: test link args ' $(pkg-config --libs bdw-gc); -lgc' failed
		expanded to: [-lgc -lpthread -ldl]
		resolved to: [-lgc -lpthread -ldl]
		error: 

goroutine 1 [running]:
github.com/goplus/llgo/internal/build.buildAllPkgs(0xc00887cf60, {0xc003e1eb40?, 0xc006f5fc80?, 0x8ed3e0?}, 0x0)
	/go/pkg/mod/github.com/goplus/llgo@v0.9.8/internal/build/build.go:344 +0xbec
github.com/goplus/llgo/internal/build.Do({0xc000024470?, 0x1?, 0x1?}, 0xc00007e5a0)
	/go/pkg/mod/github.com/goplus/llgo@v0.9.8/internal/build/build.go:214 +0xc1e
github.com/goplus/llgo/cmd/internal/run.runCmdEx(0xc000065e58?, {0xc000024470, 0x1, 0x1}, 0x2)
	/go/pkg/mod/github.com/goplus/llgo@v0.9.8/cmd/internal/run/run.go:68 +0x105
github.com/goplus/llgo/cmd/internal/run.runCmd(0xc0000ae000?, {0xc000024470?, 0x0?, 0x0?})
	/go/pkg/mod/github.com/goplus/llgo@v0.9.8/cmd/internal/run/run.go:52 +0x1d
main.main()
	/go/pkg/mod/github.com/goplus/llgo@v0.9.8/cmd/llgo/llgo.go:90 +0x4b3

llgo compiled in alpine linux3.21 docker (go version 1.23.3)，because llgo does not support alpine linux?

**Comment by aofei** [comment]
> llgo does not support alpine linux?

We haven't had any documented use cases on Alpine before. I think the issue you're having stems from Alpine's unconventional package configuration compared to most other Linux distributions, particularly regarding LLVM which is crucial for LLGo.

That said, there is a way.

To get LLGo working successfully on Alpine, you'll need to build it from source following these steps:

```bash
apk add go llvm18-dev clang18-dev lld18 pkgconf gc-dev openssl-dev zlib-dev
apk add g++ # Build only

export LLVM_CONFIG=/usr/lib/llvm18/bin/llvm-config
export CGO_CPPFLAGS="$($LLVM_CONFIG --cppflags)"
export CGO_CXXFLAGS=-std=c++17
export CGO_LDFLAGS="$($LLVM_CONFIG --ldflags) $($LLVM_CONFIG --libs all)"

go install -v -tags=byollvm -ldflags="-X github.com/goplus/llgo/xtool/env/llvm.ldLLVMConfigBin=$LLVM_CONFIG" github.com/goplus/llgo/cmd/llgo@latest
```
